# render.yaml

services:
  - type: web
    name: my-web-app
    runtime: node
    plan : free
    region : frankfurt
    repo : https://github.com/Farinesse/renderblueprintapp.git
    branch : main
    buildCommand: npm install
    startCommand: npm start
    env:
      - key: DATABASE_URL
        value: postgres://cloudplateform_user:ztHW5d8qKayfS1aIczs6FvcQ3jXBAihk@dpg-clfl8b03nsgc738v9ti0-a/cloudplateform

databases:
  - name: my-postgres-db
    region : frankfurt
    plan: free
    databaseName : cloud
    user : cloud