# render.yaml

services:
  - type: web
    name: my-web-app
    runtime: node
    plan : free
    region : frankfurt
    repo : https://github.com/Farinesse/renderblueprintapp.git
    branch : main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-postgres-db
          property: connectionString
databases:
  - name: my-postgres-db
    region : frankfurt
    plan: free
    databaseName : cloud
    user : cloud